
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPA_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataAuditPermissions
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "AuditPermissionGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid AuditPermissionGUID{ get; set; }
    	
        [Display(Name = "PermissionGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> PermissionGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "TransactionType", ResourceType = typeof(resxDbFields))]
    	public int TransactionType{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[DataType(DataType.DateTime)]
    	[Display(Name = "TransactionDateTime", ResourceType = typeof(resxDbFields))]
    	public System.DateTime TransactionDateTime{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "TransactionDateTime", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalTransactionDateTime { get { return new Portal().LocalTime(this.TransactionDateTime); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ByUserProfileGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid ByUserProfileGUID{ get; set; }
    	
    }
}
