
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPA_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataAuditActions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataAuditActions()
        {
            this.dataAuditFields = new HashSet<dataAuditFields>();
        }
    
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "AuditGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid AuditGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "UserProfileGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid UserProfileGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "RecordGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid RecordGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ActionGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid ActionGUID{ get; set; }
    	
        [StringLength(250, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "TableName", ResourceType = typeof(resxDbFields))]
    	public string TableName{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[DataType(DataType.DateTime)]
    	[Display(Name = "ExecutionTime", ResourceType = typeof(resxDbFields))]
    	public System.DateTime ExecutionTime{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ExecutionTime", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalExecutionTime { get { return new Portal().LocalTime(this.ExecutionTime); } }
    	
        [Display(Name = "Message", ResourceType = typeof(resxDbFields))]
    	public string Message{ get; set; }
    	
    
        public virtual userProfiles userProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataAuditFields> dataAuditFields { get; set; }
    }
}
