//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHM_DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SHMEntities : DbContext
    {
        public SHMEntities()
            : base("name=SHMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<codeShuttleTravelPurpose> codeShuttleTravelPurpose { get; set; }
        public virtual DbSet<codeShuttleTravelPurposeLanguage> codeShuttleTravelPurposeLanguage { get; set; }
        public virtual DbSet<userPersonalDetailsLanguage> userPersonalDetailsLanguage { get; set; }
        public virtual DbSet<codeLocations> codeLocations { get; set; }
        public virtual DbSet<codeLocationsLanguages> codeLocationsLanguages { get; set; }
        public virtual DbSet<codeReferralStatus> codeReferralStatus { get; set; }
        public virtual DbSet<codeReferralStatusLanguage> codeReferralStatusLanguage { get; set; }
        public virtual DbSet<codeDutyStations> codeDutyStations { get; set; }
        public virtual DbSet<codeDutyStationsLanguages> codeDutyStationsLanguages { get; set; }
        public virtual DbSet<codeOrganizationsInstances> codeOrganizationsInstances { get; set; }
        public virtual DbSet<codeOrganizationsInstancesLanguages> codeOrganizationsInstancesLanguages { get; set; }
        public virtual DbSet<codeOrganizationsLanguages> codeOrganizationsLanguages { get; set; }
        public virtual DbSet<userContactDetails> userContactDetails { get; set; }
        public virtual DbSet<userPersonalDetails> userPersonalDetails { get; set; }
        public virtual DbSet<userServiceHistory> userServiceHistory { get; set; }
        public virtual DbSet<dataShuttleRequestStaff> dataShuttleRequestStaff { get; set; }
        public virtual DbSet<v_StaffCurrentContact> v_StaffCurrentContact { get; set; }
        public virtual DbSet<codeJobTitlesLanguages> codeJobTitlesLanguages { get; set; }
        public virtual DbSet<codeCountriesLanguages> codeCountriesLanguages { get; set; }
        public virtual DbSet<codeCountries> codeCountries { get; set; }
        public virtual DbSet<dataShuttle> dataShuttle { get; set; }
        public virtual DbSet<dataShuttleRequest> dataShuttleRequest { get; set; }
        public virtual DbSet<dataShuttleVehicle> dataShuttleVehicle { get; set; }
        public virtual DbSet<dataShuttleRequestBoxState> dataShuttleRequestBoxState { get; set; }
        public virtual DbSet<dataShuttleRequestRoute> dataShuttleRequestRoute { get; set; }
        public virtual DbSet<dataShuttleRequestRouteStep> dataShuttleRequestRouteStep { get; set; }
        public virtual DbSet<codeVehicle> codeVehicle { get; set; }
        public virtual DbSet<dataShuttleStaff> dataShuttleStaff { get; set; }
        public virtual DbSet<StaffCoreData> StaffCoreData { get; set; }
    
        public virtual ObjectResult<RP_ShuttleReport_Result> RP_ShuttleReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string lan, string dutyStationGUID, string userPassengerGUID, string userDriverGUID, string vehicleGUID, string startLocationGUID, string endLocationGUID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var lanParameter = lan != null ?
                new ObjectParameter("Lan", lan) :
                new ObjectParameter("Lan", typeof(string));
    
            var dutyStationGUIDParameter = dutyStationGUID != null ?
                new ObjectParameter("DutyStationGUID", dutyStationGUID) :
                new ObjectParameter("DutyStationGUID", typeof(string));
    
            var userPassengerGUIDParameter = userPassengerGUID != null ?
                new ObjectParameter("UserPassengerGUID", userPassengerGUID) :
                new ObjectParameter("UserPassengerGUID", typeof(string));
    
            var userDriverGUIDParameter = userDriverGUID != null ?
                new ObjectParameter("UserDriverGUID", userDriverGUID) :
                new ObjectParameter("UserDriverGUID", typeof(string));
    
            var vehicleGUIDParameter = vehicleGUID != null ?
                new ObjectParameter("VehicleGUID", vehicleGUID) :
                new ObjectParameter("VehicleGUID", typeof(string));
    
            var startLocationGUIDParameter = startLocationGUID != null ?
                new ObjectParameter("StartLocationGUID", startLocationGUID) :
                new ObjectParameter("StartLocationGUID", typeof(string));
    
            var endLocationGUIDParameter = endLocationGUID != null ?
                new ObjectParameter("EndLocationGUID", endLocationGUID) :
                new ObjectParameter("EndLocationGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_ShuttleReport_Result>("RP_ShuttleReport", startDateParameter, endDateParameter, lanParameter, dutyStationGUIDParameter, userPassengerGUIDParameter, userDriverGUIDParameter, vehicleGUIDParameter, startLocationGUIDParameter, endLocationGUIDParameter);
        }
    }
}
