//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORG_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataPhoneDirectory
    {
        public System.Guid PhoneDirectoryGUID { get; set; }
        public Nullable<System.Guid> PhoneHolderTypeGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> DutyStationGUID { get; set; }
        public Nullable<System.Guid> DepartmentGUID { get; set; }
        public Nullable<System.Guid> JobTitleGUID { get; set; }
        public string EmailAddress { get; set; }
        public string HomeTelephoneNumberLandline { get; set; }
        public string OfficialExtensionNumber { get; set; }
        public string OfficialMobileNumber { get; set; }
        public string SATPhoneNumber { get; set; }
        public string HQExtensionNumber { get; set; }
        public string DutyStationExtensionNumber { get; set; }
        public bool Active { get; set; }
        public byte[] dataPhoneDirectoryRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
        public string CallSign { get; set; }
    
        public virtual StaffCoreData StaffCoreData { get; set; }
    }
}
