//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORG_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataStaffServiceProvided
    {
        public System.Guid StaffServiceProvidedGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<System.Guid> ServiceTypeGUID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.Guid> LastFlowStatusGUID { get; set; }
        public string LastFlowStatusName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateByGUID { get; set; }
        public Nullable<System.Guid> UpdateByGUID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Active { get; set; }
        public byte[] dataStaffServiceProvidedRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> ActivatedByGUID { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.Guid> CaneledByGUID { get; set; }
        public Nullable<System.DateTime> CaneledDate { get; set; }
    
        public virtual StaffCoreData StaffCoreData { get; set; }
    }
}
