//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORG_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataStaffOnlineTraining
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataStaffOnlineTraining()
        {
            this.dataStaffOnlineTrainingHistory = new HashSet<dataStaffOnlineTrainingHistory>();
        }
    
        public System.Guid StaffOnlineTrainingGUID { get; set; }
        public Nullable<System.Guid> OnlineTrainingTypeGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.Guid> CreatedByGUID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> TrainingStatusGUID { get; set; }
        public string StatusName { get; set; }
        public bool Active { get; set; }
        public byte[] dataStaffOnlineTrainingRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataStaffOnlineTrainingHistory> dataStaffOnlineTrainingHistory { get; set; }
        public virtual StaffCoreData StaffCoreData { get; set; }
    }
}
