//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proGres_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDataProcessGroup
    {
        public System.Guid ProcessingGroupGUID { get; set; }
        public short ProcessingGroupTypeCode { get; set; }
        public string ProcessingGroupNumber { get; set; }
        public string ProcessingGroupLegacyID { get; set; }
        public string ProcessingGroupGovtNumber { get; set; }
        public string ProcessingGroupFileNumber { get; set; }
        public string ProcessingGroupFormNumber { get; set; }
        public string CurrentRationCardNumber { get; set; }
        public Nullable<bool> ProcessingGroupActive { get; set; }
        public short ProcessingGroupSize { get; set; }
        public short TotalGroupSize { get; set; }
        public string OriginalProcessingGroupNumber { get; set; }
        public string ResponsibleUserID { get; set; }
        public System.DateTime ProcessingGroupRegistrationDate { get; set; }
        public string CaseSource { get; set; }
        public string ProcessingGroupStatusCode { get; set; }
        public System.DateTime ProcessGroupStatusDate { get; set; }
        public string ProcessingGroupComments { get; set; }
    }
}
