
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBS_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class v_UserBillDetailsGrouped
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EDMXID", ResourceType = typeof(resxDbFields))]
    	public long EDMXID{ get; set; }
    	
        [Display(Name = "NumberOfCalls", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> NumberOfCalls{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "UserBillGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid UserBillGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CallingNumber", ResourceType = typeof(resxDbFields))]
    	public string CallingNumber{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CalledNumber", ResourceType = typeof(resxDbFields))]
    	public string CalledNumber{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CalledStaffName", ResourceType = typeof(resxDbFields))]
    	public string CalledStaffName{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IsConfirmed", ResourceType = typeof(resxDbFields))]
    	public bool IsConfirmed{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IsPrivate", ResourceType = typeof(resxDbFields))]
    	public bool IsPrivate{ get; set; }
    	
        [Display(Name = "Comments", ResourceType = typeof(resxDbFields))]
    	public string Comments{ get; set; }
    	
        [Display(Name = "LastConfirmation", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> LastConfirmation{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "BillLocked", ResourceType = typeof(resxDbFields))]
    	public bool BillLocked{ get; set; }
    	
        [Display(Name = "AutomatedBySystem", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> AutomatedBySystem{ get; set; }
    	
        [Display(Name = "UserOverride", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> UserOverride{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IsFirstOpen", ResourceType = typeof(resxDbFields))]
    	public bool IsFirstOpen{ get; set; }
    	
        [Display(Name = "TotalDurationInSeconds", ResourceType = typeof(resxDbFields))]
    	public Nullable<long> TotalDurationInSeconds{ get; set; }
    	
        [Display(Name = "TotalDurationMinutes", ResourceType = typeof(resxDbFields))]
    	public Nullable<long> TotalDurationMinutes{ get; set; }
    	
        [Display(Name = "TotalCallCost", ResourceType = typeof(resxDbFields))]
    	public Nullable<long> TotalCallCost{ get; set; }
    	
    }
}
