
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataCardIndividualInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataCardIndividualInfo()
        {
            this.dataCardIssued = new HashSet<dataCardIssued>();
        }
    
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CardIndividualInfoGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid CardIndividualInfoGUID{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IndividualID", ResourceType = typeof(resxDbFields))]
    	public string IndividualID{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CaseNumber", ResourceType = typeof(resxDbFields))]
    	public string CaseNumber{ get; set; }
    	
        [StringLength(70, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "FullName_EN", ResourceType = typeof(resxDbFields))]
    	public string FullName_EN{ get; set; }
    	
        [StringLength(57, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "FullName_AR", ResourceType = typeof(resxDbFields))]
    	public string FullName_AR{ get; set; }
    	
        [StringLength(2, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Sex", ResourceType = typeof(resxDbFields))]
    	public string Sex{ get; set; }
    	
        [DataType(DataType.Date)]
    	[Display(Name = "DateOfBrith", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DateOfBrith{ get; set; }
    	
        [StringLength(15, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Category", ResourceType = typeof(resxDbFields))]
    	public string Category{ get; set; }
    	
        [DataType(DataType.Date)]
    	[Display(Name = "ArrivalDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ArrivalDate{ get; set; }
    	
        [Display(Name = "ArrivalEstimation", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> ArrivalEstimation{ get; set; }
    	
        [StringLength(10, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CountyCodeA3", ResourceType = typeof(resxDbFields))]
    	public string CountyCodeA3{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ShowNationality", ResourceType = typeof(resxDbFields))]
    	public bool ShowNationality{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataCardIndividualInfoRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataCardIssued> dataCardIssued { get; set; }
    }
}
