//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeOperationsLanguages
    {
        public System.Guid OperationLanguageGUID { get; set; }
        public System.Guid OperationGUID { get; set; }
        public string LanguageID { get; set; }
        public string OperationDescription { get; set; }
        public bool Active { get; set; }
        public byte[] codeOperationsLanguagesRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeOperations codeOperations { get; set; }
    }
}
