//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeMedicalManufacturerLanguage
    {
        public System.Guid MedicalManufacturerLanguageGUID { get; set; }
        public System.Guid MedicalManufacturerGUID { get; set; }
        public string LanguageID { get; set; }
        public string MedicalManufacturerDescription { get; set; }
        public bool Active { get; set; }
        public byte[] codeMedicalManufacturerLanguageRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeMedicalManufacturer codeMedicalManufacturer { get; set; }
    }
}
