//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codePmdUnitOfAchievement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codePmdUnitOfAchievement()
        {
            this.codePmdUnitOfAchievementLanguages = new HashSet<codePmdUnitOfAchievementLanguages>();
        }
    
        public System.Guid UnitOfAchievementGUID { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public byte[] codePmdUnitOfAchievementRowVersion { get; set; }
        public string UnitOfAchievementCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codePmdUnitOfAchievementLanguages> codePmdUnitOfAchievementLanguages { get; set; }
    }
}
