//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeDutyStations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeDutyStations()
        {
            this.StaffCoreDataHistory = new HashSet<StaffCoreDataHistory>();
            this.userProfiles = new HashSet<userProfiles>();
            this.codeAHDEntitlementTypePerDutyStation = new HashSet<codeAHDEntitlementTypePerDutyStation>();
            this.codeDutyStationsLanguages = new HashSet<codeDutyStationsLanguages>();
            this.codeISSStock = new HashSet<codeISSStock>();
            this.codeDutyStationsConfigurations = new HashSet<codeDutyStationsConfigurations>();
            this.codePartnerCenter = new HashSet<codePartnerCenter>();
            this.codeWarehouse = new HashSet<codeWarehouse>();
            this.dataMissionReportForm = new HashSet<dataMissionReportForm>();
        }
    
        public System.Guid DutyStationGUID { get; set; }
        public System.Guid CountryGUID { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public bool Active { get; set; }
        public byte[] codeDutyStationsRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDutyStation { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string DutyStationCode { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string TZ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffCoreDataHistory> StaffCoreDataHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userProfiles> userProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeAHDEntitlementTypePerDutyStation> codeAHDEntitlementTypePerDutyStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeDutyStationsLanguages> codeDutyStationsLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeISSStock> codeISSStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeDutyStationsConfigurations> codeDutyStationsConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codePartnerCenter> codePartnerCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouse> codeWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMissionReportForm> dataMissionReportForm { get; set; }
    }
}
