//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeDASDestinationUnitFocalPoint
    {
        public System.Guid DestinationUnitFocalPointGUID { get; set; }
        public Nullable<System.Guid> DestinationUnitGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public string FullName { get; set; }
        public bool Active { get; set; }
        public byte[] codeDASDestinationUnitFocalPointRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual codeDASDestinationUnit codeDASDestinationUnit { get; set; }
        public virtual userAccounts userAccounts { get; set; }
    }
}
