//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeMedicalItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeMedicalItem()
        {
            this.dataMedicalItemInputDetail = new HashSet<dataMedicalItemInputDetail>();
        }
    
        public System.Guid MedicalItemGUID { get; set; }
        public System.Guid MedicalGenericNameGUID { get; set; }
        public string BrandName { get; set; }
        public string DoseQuantity { get; set; }
        public System.Guid MedicalDoseUnitGUID { get; set; }
        public System.Guid MedicalPharmacologicalFormGUID { get; set; }
        public Nullable<double> PackingUnit { get; set; }
        public System.Guid MedicalPackingUnitGUID { get; set; }
        public System.Guid MedicalManufacturerGUID { get; set; }
        public string LicenseNoDate { get; set; }
        public System.Guid SourceGUID { get; set; }
        public System.Guid MedicalTreatmentGUID { get; set; }
        public System.Guid MedicalRouteAdministrationGUID { get; set; }
        public int TotalDispatchedItems { get; set; }
        public double RemainingItemsQuantity { get; set; }
        public string Barcode { get; set; }
        public bool Active { get; set; }
        public byte[] codeMedicalItemRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int Sequance { get; set; }
    
        public virtual codeMedicalGenericName codeMedicalGenericName { get; set; }
        public virtual codeMedicalManufacturer codeMedicalManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMedicalItemInputDetail> dataMedicalItemInputDetail { get; set; }
    }
}
