//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeLanguages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeLanguages()
        {
            this.userPersonalDetails = new HashSet<userPersonalDetails>();
        }
    
        public string LanguageID { get; set; }
        public string LanguageNameEN { get; set; }
        public string LanguageNameLocal { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SortID { get; set; }
        public byte[] codeLanguagesRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPersonalDetails> userPersonalDetails { get; set; }
    }
}
