//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codePmdIndicatorLanguage
    {
        public System.Guid IndicatorLanguageGUID { get; set; }
        public System.Guid IndicatorGUID { get; set; }
        public string LanguageID { get; set; }
        public string IndicatorDescription { get; set; }
        public string IndicatorGuidance { get; set; }
        public bool Active { get; set; }
        public byte[] codePmdIndicatorLanguageRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codePmdIndicator codePmdIndicator { get; set; }
    }
}
