//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class code4WSCamps
    {
        public System.Guid CampGUID { get; set; }
        public string CampID { get; set; }
        public string CampName { get; set; }
        public string CommCode { get; set; }
        public string CommName { get; set; }
        public string SDName { get; set; }
        public bool Active { get; set; }
        public byte[] code4WSCampsRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
