//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeOfficesConfigurations
    {
        public System.Guid OfficeConfigurationGUID { get; set; }
        public Nullable<System.Guid> OrganizationInstanceGUID { get; set; }
        public Nullable<System.Guid> OfficeGUID { get; set; }
        public bool Active { get; set; }
        public byte[] codeOfficesConfigurationsRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeOffices codeOffices { get; set; }
        public virtual codeOrganizationsInstances codeOrganizationsInstances { get; set; }
    }
}
