//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeElectionCorrespondenceTypeLanguage
    {
        public System.Guid ElectionCorrespondenceTypeLanguageGUID { get; set; }
        public Nullable<System.Guid> ElectionCorrespondenceTypeGUID { get; set; }
        public string ElectionCorrespondenceTypeDescription { get; set; }
        public string LanguageID { get; set; }
        public bool Active { get; set; }
        public byte[] codeElectionCorrespondenceTypeLanguageRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeElectionCorrespondenceType codeElectionCorrespondenceType { get; set; }
    }
}
