//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeSipPopulationGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeSipPopulationGroup()
        {
            this.codeSipPopulationGroupLanguages = new HashSet<codeSipPopulationGroupLanguages>();
        }
    
        public System.Guid SipPopulationGroupGUID { get; set; }
        public string SipPopulationGroupCode { get; set; }
        public bool Active { get; set; }
        public byte[] codeSipPopulationGroupRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeSipPopulationGroupLanguages> codeSipPopulationGroupLanguages { get; set; }
    }
}
