//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataMedicalBeneficiary
    {
        public System.Guid MedicalBeneficiaryGUID { get; set; }
        public System.Guid BeneficiaryTypeGUID { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string UNHCRNumber { get; set; }
        public string RefugeeFullName { get; set; }
        public string NationalityCode { get; set; }
        public System.Guid GenderGUID { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public Nullable<System.Guid> OrganizationInstanceGUID { get; set; }
        public bool Active { get; set; }
        public byte[] dataMedicalBeneficiaryRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
