//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataPartnerReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataPartnerReport()
        {
            this.dataPartnerReportCompiled = new HashSet<dataPartnerReportCompiled>();
        }
    
        public System.Guid PartnerReportGUID { get; set; }
        public System.Guid PartnerCenterGUID { get; set; }
        public bool Active { get; set; }
        public byte[] dataPartnerReportRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codePartnerCenter codePartnerCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataPartnerReportCompiled> dataPartnerReportCompiled { get; set; }
    }
}
