//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userApplicationToken
    {
        public System.Guid ApplictionToken { get; set; }
        public Nullable<System.Guid> UserProfileGUID { get; set; }
        public Nullable<System.Guid> ApplicationGUID { get; set; }
        public string Token { get; set; }
        public bool Active { get; set; }
        public byte[] userApplicationTokenRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeApplications codeApplications { get; set; }
        public virtual userProfiles userProfiles { get; set; }
    }
}
