//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRegistrationQueue
    {
        public System.Guid UserRegistrationQueueGUID { get; set; }
        public System.Guid UserGUID { get; set; }
        public Nullable<System.Guid> SponsorUserProfileGUID { get; set; }
        public bool SponsorConfirmed { get; set; }
        public Nullable<System.Guid> OrganizationInstanceGUID { get; set; }
        public string TimeZone { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<System.Guid> SecurityQuestionGUID { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<int> AccountStatusID { get; set; }
        public string LanguageID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.Guid> FromDate { get; set; }
        public Nullable<System.Guid> ToDate { get; set; }
        public bool Active { get; set; }
        public byte[] userRegistrationQueueRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> JobTitleGUID { get; set; }
    }
}
