//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataMissionActionTaken
    {
        public System.Guid MissionActionTakenGUID { get; set; }
        public Nullable<System.Guid> MissionActionRequiredGUID { get; set; }
        public Nullable<System.Guid> CreatedByGUID { get; set; }
        public Nullable<System.Guid> ActionStatusGUID { get; set; }
        public string ActionTakenName { get; set; }
        public Nullable<System.DateTime> ActionTakenDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Active { get; set; }
        public byte[] dataMissionActionTakenRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual userAccounts userAccounts { get; set; }
        public virtual dataMissionActionRequired dataMissionActionRequired { get; set; }
    }
}
