//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataMissionReportFormFlow
    {
        public System.Guid MissionReportFormFlowGUID { get; set; }
        public Nullable<System.Guid> MissionReportFormGUID { get; set; }
        public Nullable<System.Guid> RequestStatusGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<bool> IsLastAction { get; set; }
        public Nullable<System.Guid> CreatedByGUID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
        public byte[] dataMissionReportFormFlowRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual userAccounts userAccounts { get; set; }
        public virtual userAccounts userAccounts1 { get; set; }
        public virtual dataMissionReportForm dataMissionReportForm { get; set; }
    }
}
