//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_vMissionReportForm
    {
        public Nullable<long> RowId { get; set; }
        public System.Guid MissionReportFormGUID { get; set; }
        public string MissionStartDate { get; set; }
        public string MissionEndDate { get; set; }
        public string MissionCode { get; set; }
        public Nullable<int> MissionNumber { get; set; }
        public Nullable<int> MonthMissionStartDate { get; set; }
        public Nullable<int> YearMissionStartDate { get; set; }
        public string MissionStatus { get; set; }
        public string FromOffice { get; set; }
        public string Governorate { get; set; }
        public string District { get; set; }
        public string SubDistrict { get; set; }
        public string Community { get; set; }
        public string Address { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Is_AnyPresence_Other_Organization_ { get; set; }
        public string Gaps { get; set; }
        public string Recommendations { get; set; }
        public string ActionRequired { get; set; }
        public string ActionTaken { get; set; }
        public string LinkToMissionReport { get; set; }
        public string Is_There_Mission_Report_ { get; set; }
        public string Comments { get; set; }
        public Nullable<double> Coordinates { get; set; }
    }
}
