//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSEntities : DbContext
    {
        public IMSEntities()
            : base("name=IMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StaffCoreData> StaffCoreData { get; set; }
        public virtual DbSet<userAccounts> userAccounts { get; set; }
        public virtual DbSet<userPersonalDetails> userPersonalDetails { get; set; }
        public virtual DbSet<userPersonalDetailsLanguage> userPersonalDetailsLanguage { get; set; }
        public virtual DbSet<userServiceHistory> userServiceHistory { get; set; }
        public virtual DbSet<codeCountries> codeCountries { get; set; }
        public virtual DbSet<codeCountriesLanguages> codeCountriesLanguages { get; set; }
        public virtual DbSet<codeDepartments> codeDepartments { get; set; }
        public virtual DbSet<codeDepartmentsLanguages> codeDepartmentsLanguages { get; set; }
        public virtual DbSet<codeDutyStations> codeDutyStations { get; set; }
        public virtual DbSet<codeDutyStationsLanguages> codeDutyStationsLanguages { get; set; }
        public virtual DbSet<codeIMSHumanitarianNeed> codeIMSHumanitarianNeed { get; set; }
        public virtual DbSet<codeIMSHumanitarianNeedLanguage> codeIMSHumanitarianNeedLanguage { get; set; }
        public virtual DbSet<codeIMSMissionChallenge> codeIMSMissionChallenge { get; set; }
        public virtual DbSet<codeIMSMissionChallengeLanguage> codeIMSMissionChallengeLanguage { get; set; }
        public virtual DbSet<codeIMSOngoingResponse> codeIMSOngoingResponse { get; set; }
        public virtual DbSet<codeIMSOngoingResponseLanguage> codeIMSOngoingResponseLanguage { get; set; }
        public virtual DbSet<codeIMSVisitObjective> codeIMSVisitObjective { get; set; }
        public virtual DbSet<codeIMSVisitObjectiveCategory> codeIMSVisitObjectiveCategory { get; set; }
        public virtual DbSet<codeIMSVisitObjectiveCategoryLanguage> codeIMSVisitObjectiveCategoryLanguage { get; set; }
        public virtual DbSet<codeIMSVisitObjectiveLanguage> codeIMSVisitObjectiveLanguage { get; set; }
        public virtual DbSet<codeJobTitles> codeJobTitles { get; set; }
        public virtual DbSet<codeJobTitlesLanguages> codeJobTitlesLanguages { get; set; }
        public virtual DbSet<codeLocations> codeLocations { get; set; }
        public virtual DbSet<codeLocationsLanguages> codeLocationsLanguages { get; set; }
        public virtual DbSet<codeMissionOfficeSource> codeMissionOfficeSource { get; set; }
        public virtual DbSet<codeMissionOfficeSourceLanguage> codeMissionOfficeSourceLanguage { get; set; }
        public virtual DbSet<codeTables> codeTables { get; set; }
        public virtual DbSet<codeTablesValues> codeTablesValues { get; set; }
        public virtual DbSet<codeTablesValuesLanguages> codeTablesValuesLanguages { get; set; }
        public virtual DbSet<dataMissionActionRequired> dataMissionActionRequired { get; set; }
        public virtual DbSet<dataMissionActionTaken> dataMissionActionTaken { get; set; }
        public virtual DbSet<dataMissionReportDepartment> dataMissionReportDepartment { get; set; }
        public virtual DbSet<dataMissionReportDocument> dataMissionReportDocument { get; set; }
        public virtual DbSet<dataMissionReportForm> dataMissionReportForm { get; set; }
        public virtual DbSet<dataMissionReportFormChallenge> dataMissionReportFormChallenge { get; set; }
        public virtual DbSet<dataMissionReportFormFlow> dataMissionReportFormFlow { get; set; }
        public virtual DbSet<dataMissionReportFormFlowNotification> dataMissionReportFormFlowNotification { get; set; }
        public virtual DbSet<dataMissionReportFormHumanitarianNeed> dataMissionReportFormHumanitarianNeed { get; set; }
        public virtual DbSet<dataMissionReportFormMember> dataMissionReportFormMember { get; set; }
        public virtual DbSet<dataMissionReportFormOngoingResponse> dataMissionReportFormOngoingResponse { get; set; }
        public virtual DbSet<dataMissionReportFormVisitObjective> dataMissionReportFormVisitObjective { get; set; }
        public virtual DbSet<dataMissionReportPhoto> dataMissionReportPhoto { get; set; }
        public virtual DbSet<dataTempMissionAction> dataTempMissionAction { get; set; }
        public virtual DbSet<IMS_vMissionReportForm> IMS_vMissionReportForm { get; set; }
        public virtual DbSet<v_IMSMissionReportDepartment> v_IMSMissionReportDepartment { get; set; }
        public virtual DbSet<v_IMSMissionReportFormChallenge> v_IMSMissionReportFormChallenge { get; set; }
        public virtual DbSet<v_IMSMissionReportFormHumanitarianNeed> v_IMSMissionReportFormHumanitarianNeed { get; set; }
        public virtual DbSet<v_IMSMissionReportFormOngoingResponse> v_IMSMissionReportFormOngoingResponse { get; set; }
        public virtual DbSet<v_IMSMissionReportVisitObjective> v_IMSMissionReportVisitObjective { get; set; }
        public virtual DbSet<v_IMSTrackMissionReportForm> v_IMSTrackMissionReportForm { get; set; }
        public virtual DbSet<v_TrackFormDuplication> v_TrackFormDuplication { get; set; }
        public virtual DbSet<v_trackMissionByCategoryING> v_trackMissionByCategoryING { get; set; }
    }
}
