//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_trackMissionByCategoryING
    {
        public string MissionCode { get; set; }
        public string Participants_staff_member { get; set; }
        public string Type_of_mission_ { get; set; }
        public string Detailed_purpose_of_the_mission_ { get; set; }
        public System.DateTime MissionStartDate { get; set; }
        public Nullable<int> MonthMissionStartDate { get; set; }
        public Nullable<int> YearMissionStartDate { get; set; }
        public string MissionStatus { get; set; }
        public string Governorate { get; set; }
        public string Community { get; set; }
    }
}
