
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataStaffRenwalResidency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataStaffRenwalResidency()
        {
            this.dataStaffRenwalResidencyFlow = new HashSet<dataStaffRenwalResidencyFlow>();
        }
    
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "StaffRenwalResidencyGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid StaffRenwalResidencyGUID{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "RefNumber", ResourceType = typeof(resxDbFields))]
    	public string RefNumber{ get; set; }
    	
        [Display(Name = "StaffGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> StaffGUID{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "PassportNumber", ResourceType = typeof(resxDbFields))]
    	public string PassportNumber{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "PassportValidityDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> PassportValidityDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "PassportValidityDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalPassportValidityDate { get { return new Portal().LocalTime(this.PassportValidityDate); } }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EnJobTitle", ResourceType = typeof(resxDbFields))]
    	public string EnJobTitle{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ArJobTitle", ResourceType = typeof(resxDbFields))]
    	public string ArJobTitle{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EnOffice", ResourceType = typeof(resxDbFields))]
    	public string EnOffice{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ArOffice", ResourceType = typeof(resxDbFields))]
    	public string ArOffice{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ContractStartDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ContractStartDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ContractStartDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalContractStartDate { get { return new Portal().LocalTime(this.ContractStartDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ContractEndDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ContractEndDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ContractEndDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalContractEndDate { get { return new Portal().LocalTime(this.ContractEndDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "CurrentResidencyEndDateSent", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> CurrentResidencyEndDateSent{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "CurrentResidencyEndDateSent", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalCurrentResidencyEndDateSent { get { return new Portal().LocalTime(this.CurrentResidencyEndDateSent); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "CurrentResidencyEndDateStampd", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> CurrentResidencyEndDateStampd{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "CurrentResidencyEndDateStampd", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalCurrentResidencyEndDateStampd { get { return new Portal().LocalTime(this.CurrentResidencyEndDateStampd); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "CreateDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> CreateDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "CreateDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalCreateDate { get { return new Portal().LocalTime(this.CreateDate); } }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "LastFlowStatus", ResourceType = typeof(resxDbFields))]
    	public string LastFlowStatus{ get; set; }
    	
        [Display(Name = "CreateByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> CreateByGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataStaffRenwalResidencyRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
        [Display(Name = "Archived", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> Archived{ get; set; }
    	
        [Display(Name = "LastFlowStatusGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> LastFlowStatusGUID{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EnStaffName", ResourceType = typeof(resxDbFields))]
    	public string EnStaffName{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ArStaffName", ResourceType = typeof(resxDbFields))]
    	public string ArStaffName{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EnDeptName", ResourceType = typeof(resxDbFields))]
    	public string EnDeptName{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ArDeptName", ResourceType = typeof(resxDbFields))]
    	public string ArDeptName{ get; set; }
    	
        [StringLength(10, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Gender", ResourceType = typeof(resxDbFields))]
    	public string Gender{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EnNationality", ResourceType = typeof(resxDbFields))]
    	public string EnNationality{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ArNationality", ResourceType = typeof(resxDbFields))]
    	public string ArNationality{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ReturnDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ReturnDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ReturnDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalReturnDate { get { return new Portal().LocalTime(this.ReturnDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "SentDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> SentDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "SentDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalSentDate { get { return new Portal().LocalTime(this.SentDate); } }
    	
        [Display(Name = "FormTypeGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> FormTypeGUID{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "FormTypeName", ResourceType = typeof(resxDbFields))]
    	public string FormTypeName{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "EntryDateToSyria", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> EntryDateToSyria{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "EntryDateToSyria", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalEntryDateToSyria { get { return new Portal().LocalTime(this.EntryDateToSyria); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "NextExtensionRequest", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> NextExtensionRequest{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "NextExtensionRequest", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalNextExtensionRequest { get { return new Portal().LocalTime(this.NextExtensionRequest); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DepartureDateFromSyria", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DepartureDateFromSyria{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DepartureDateFromSyria", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDepartureDateFromSyria { get { return new Portal().LocalTime(this.DepartureDateFromSyria); } }
    	
    
        public virtual userPersonalDetails userPersonalDetails { get; set; }
        public virtual userAccounts userAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataStaffRenwalResidencyFlow> dataStaffRenwalResidencyFlow { get; set; }
    }
}
