
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataMissionRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataMissionRequest()
        {
            this.dataMissionRequestDocument = new HashSet<dataMissionRequestDocument>();
            this.dataMissionRequestFlow = new HashSet<dataMissionRequestFlow>();
            this.dataMissionRequestItinerary = new HashSet<dataMissionRequestItinerary>();
            this.dataMissionRequestTraveler = new HashSet<dataMissionRequestTraveler>();
        }
    
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "MissionRequestGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid MissionRequestGUID{ get; set; }
    	
        [Display(Name = "SequenceNumber", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> SequenceNumber{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ReferenceNumber", ResourceType = typeof(resxDbFields))]
    	public string ReferenceNumber{ get; set; }
    	
        [Display(Name = "StaffGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> StaffGUID{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "StaffName", ResourceType = typeof(resxDbFields))]
    	public string StaffName{ get; set; }
    	
        [Display(Name = "Grade", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> Grade{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "JobTitle", ResourceType = typeof(resxDbFields))]
    	public string JobTitle{ get; set; }
    	
        [Display(Name = "DepartmentGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> DepartmentGUID{ get; set; }
    	
        [Display(Name = "DutyStationGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> DutyStationGUID{ get; set; }
    	
        [Display(Name = "VersionNumber", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> VersionNumber{ get; set; }
    	
        [Display(Name = "MissionYear", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> MissionYear{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "MissionCode", ResourceType = typeof(resxDbFields))]
    	public string MissionCode{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DepartureDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DepartureDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DepartureDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDepartureDate { get { return new Portal().LocalTime(this.DepartureDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ReturnDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ReturnDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ReturnDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalReturnDate { get { return new Portal().LocalTime(this.ReturnDate); } }
    	
        [Display(Name = "TypeOfTravelGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> TypeOfTravelGUID{ get; set; }
    	
        [Display(Name = "TypeOfMissionGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> TypeOfMissionGUID{ get; set; }
    	
        [Display(Name = "PurposeOfMission", ResourceType = typeof(resxDbFields))]
    	public string PurposeOfMission{ get; set; }
    	
        [Display(Name = "HasDamascusTransit", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> HasDamascusTransit{ get; set; }
    	
        [Display(Name = "IsMissionCombinedWithLeave", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> IsMissionCombinedWithLeave{ get; set; }
    	
        [Display(Name = "IsMissionCombinedWithRR", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> IsMissionCombinedWithRR{ get; set; }
    	
        [Display(Name = "RestAndRecuperationLeaveGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> RestAndRecuperationLeaveGUID{ get; set; }
    	
        [Display(Name = "PaymentMethodGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> PaymentMethodGUID{ get; set; }
    	
        [Display(Name = "BudgetComments", ResourceType = typeof(resxDbFields))]
    	public string BudgetComments{ get; set; }
    	
        [Display(Name = "BudgetTypeGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> BudgetTypeGUID{ get; set; }
    	
        [Display(Name = "AdminApprovedByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> AdminApprovedByGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "AdminApprovedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> AdminApprovedDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "AdminApprovedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalAdminApprovedDate { get { return new Portal().LocalTime(this.AdminApprovedDate); } }
    	
        [StringLength(4000, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "AdminComments", ResourceType = typeof(resxDbFields))]
    	public string AdminComments{ get; set; }
    	
        [Display(Name = "AuthorizedByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> AuthorizedByGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "AuthorizedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> AuthorizedDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "AuthorizedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalAuthorizedDate { get { return new Portal().LocalTime(this.AuthorizedDate); } }
    	
        [StringLength(4000, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "AuthorizedComment", ResourceType = typeof(resxDbFields))]
    	public string AuthorizedComment{ get; set; }
    	
        [Display(Name = "AuthByDeputyRepresentativeGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> AuthByDeputyRepresentativeGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "AuthByDeputyRepDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> AuthByDeputyRepDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "AuthByDeputyRepDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalAuthByDeputyRepDate { get { return new Portal().LocalTime(this.AuthByDeputyRepDate); } }
    	
        [Display(Name = "AuthByRepresentativeGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> AuthByRepresentativeGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "AuthByRepDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> AuthByRepDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "AuthByRepDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalAuthByRepDate { get { return new Portal().LocalTime(this.AuthByRepDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "CaneledDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> CaneledDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "CaneledDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalCaneledDate { get { return new Portal().LocalTime(this.CaneledDate); } }
    	
        [StringLength(500, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ReasonOfCancellation", ResourceType = typeof(resxDbFields))]
    	public string ReasonOfCancellation{ get; set; }
    	
        [Display(Name = "CanceledByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> CanceledByGUID{ get; set; }
    	
        [Display(Name = "LastFlowStatusGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> LastFlowStatusGUID{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "LastFlowStatus", ResourceType = typeof(resxDbFields))]
    	public string LastFlowStatus{ get; set; }
    	
        [StringLength(2000, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Comments", ResourceType = typeof(resxDbFields))]
    	public string Comments{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "CreateDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> CreateDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "CreateDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalCreateDate { get { return new Portal().LocalTime(this.CreateDate); } }
    	
        [Display(Name = "CreateByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> CreateByGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataMissionRequestRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
        [Display(Name = "Archived", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> Archived{ get; set; }
    	
        [Display(Name = "HeadOfUnitApprovedByGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> HeadOfUnitApprovedByGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "HeadOfUnitApprovedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> HeadOfUnitApprovedDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "HeadOfUnitApprovedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalHeadOfUnitApprovedDate { get { return new Portal().LocalTime(this.HeadOfUnitApprovedDate); } }
    	
        [StringLength(4000, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HeadOfUnitComments", ResourceType = typeof(resxDbFields))]
    	public string HeadOfUnitComments{ get; set; }
    	
    
        public virtual dataRestAndRecuperationRequest dataRestAndRecuperationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMissionRequestDocument> dataMissionRequestDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMissionRequestFlow> dataMissionRequestFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMissionRequestItinerary> dataMissionRequestItinerary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataMissionRequestTraveler> dataMissionRequestTraveler { get; set; }
    }
}
