
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataAHDInternationalStaffEntitlementRoomTaken
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "InternationalStaffEntitlementRoomTakenGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid InternationalStaffEntitlementRoomTakenGUID{ get; set; }
    	
        [Display(Name = "InternationalStaffEntitlementDetailGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> InternationalStaffEntitlementDetailGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "StartDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> StartDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "StartDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalStartDate { get { return new Portal().LocalTime(this.StartDate); } }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "EndDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> EndDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "EndDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalEndDate { get { return new Portal().LocalTime(this.EndDate); } }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ReplacedByName", ResourceType = typeof(resxDbFields))]
    	public string ReplacedByName{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Comments", ResourceType = typeof(resxDbFields))]
    	public string Comments{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataAHDInternationalStaffEntitlementRoomTakenRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
        [Display(Name = "Archived", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> Archived{ get; set; }
    	
    
        public virtual dataAHDInternationalStaffEntitlementDetail dataAHDInternationalStaffEntitlementDetail { get; set; }
    }
}
