
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class v_VehicleMaintenanceRequest
    {
        [Display(Name = "VehicleGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> VehicleGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VehicleMaintenanceRequestGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid VehicleMaintenanceRequestGUID{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "RequestNumber", ResourceType = typeof(resxDbFields))]
    	public string RequestNumber{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "RequestDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> RequestDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "RequestDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalRequestDate { get { return new Portal().LocalTime(this.RequestDate); } }
    	
        [Display(Name = "RequestYear", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> RequestYear{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EngineNumber", ResourceType = typeof(resxDbFields))]
    	public string EngineNumber{ get; set; }
    	
        [StringLength(150, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ChassisNumber", ResourceType = typeof(resxDbFields))]
    	public string ChassisNumber{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "LastRenewalDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LastRenewalDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "LastRenewalDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalLastRenewalDate { get { return new Portal().LocalTime(this.LastRenewalDate); } }
    	
        [Display(Name = "ManufacturingYear", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ManufacturingYear{ get; set; }
    	
        [Display(Name = "PlateNumber", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> PlateNumber{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VehicleNumber", ResourceType = typeof(resxDbFields))]
    	public string VehicleNumber{ get; set; }
    	
        [StringLength(256, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VehicleType", ResourceType = typeof(resxDbFields))]
    	public string VehicleType{ get; set; }
    	
        [StringLength(256, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VehicleColor", ResourceType = typeof(resxDbFields))]
    	public string VehicleColor{ get; set; }
    	
        [StringLength(256, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VehicleModel", ResourceType = typeof(resxDbFields))]
    	public string VehicleModel{ get; set; }
    	
    }
}
