//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RES_Repo.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resxMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resxMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RES_Repo.Globalization.resxMessages", typeof(resxMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not allowed for maximum candidates.
        /// </summary>
        public static string CheckMaxmimumCandiates {
            get {
                return ResourceManager.GetString("CheckMaxmimumCandiates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not allowed for total female candidates.
        /// </summary>
        public static string CheckMaxmimumFemaleCandiates {
            get {
                return ResourceManager.GetString("CheckMaxmimumFemaleCandiates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not allowed for total male candidates.
        /// </summary>
        public static string CheckMaxmimumMaleCandiates {
            get {
                return ResourceManager.GetString("CheckMaxmimumMaleCandiates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not allowed for minimum candidates.
        /// </summary>
        public static string CheckMinimumCandiates {
            get {
                return ResourceManager.GetString("CheckMinimumCandiates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimum number of votes allowed is bigger than the maximum number of votes allowed.
        /// </summary>
        public static string CheckMinimumVotes {
            get {
                return ResourceManager.GetString("CheckMinimumVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to chose at least .
        /// </summary>
        public static string ChoseAppropriateNumberOFCanidates {
            get {
                return ResourceManager.GetString("ChoseAppropriateNumberOFCanidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Responsibility.
        /// </summary>
        public static string ConfirmResponsibility {
            get {
                return ResourceManager.GetString("ConfirmResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully.
        /// </summary>
        public static string DeleteNotify {
            get {
                return ResourceManager.GetString("DeleteNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Name in selected language already exists.
        /// </summary>
        public static string ElecetionAlreadyExists {
            get {
                return ResourceManager.GetString("ElecetionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You exceed the allowed maximum number of Candidates which is.
        /// </summary>
        public static string ElectionExceedAllowedCandidates {
            get {
                return ResourceManager.GetString("ElectionExceedAllowedCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Start this Election kindly click on the button below.
        /// </summary>
        public static string ElectionStartMessage {
            get {
                return ResourceManager.GetString("ElectionStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Candidates for this election is.
        /// </summary>
        public static string ElectionTotalCandidates {
            get {
                return ResourceManager.GetString("ElectionTotalCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Election.
        /// </summary>
        public static string ElectionWelcomeMessage {
            get {
                return ResourceManager.GetString("ElectionWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail .
        /// </summary>
        public static string FailNotify {
            get {
                return ResourceManager.GetString("FailNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to be imported must contain two columns. The first column is the full name of the vote and the second column must be his email.
        /// </summary>
        public static string FileImportStaffWarning {
            get {
                return ResourceManager.GetString("FileImportStaffWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t chose Any candidate.
        /// </summary>
        public static string NoCandidateChosen {
            get {
                return ResourceManager.GetString("NoCandidateChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to vote.
        /// </summary>
        public static string NotAllowedToVote {
            get {
                return ResourceManager.GetString("NotAllowedToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Value not in the match range.
        /// </summary>
        public static string RangeConditionValue {
            get {
                return ResourceManager.GetString("RangeConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Close Date.
        /// </summary>
        public static string RequiredCloseDate {
            get {
                return ResourceManager.GetString("RequiredCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Duty Station.
        /// </summary>
        public static string RequiredDutyStationGUID {
            get {
                return ResourceManager.GetString("RequiredDutyStationGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Organization.
        /// </summary>
        public static string RequiredOrganizationInstanceGUID {
            get {
                return ResourceManager.GetString("RequiredOrganizationInstanceGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Start Date.
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Time Zone.
        /// </summary>
        public static string RequiredTimeZone {
            get {
                return ResourceManager.GetString("RequiredTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Title.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Entry.
        /// </summary>
        public static string ReuiredEntry {
            get {
                return ResourceManager.GetString("ReuiredEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successfully.
        /// </summary>
        public static string SaveNotify {
            get {
                return ResourceManager.GetString("SaveNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be Greater than Close Date.
        /// </summary>
        public static string StartDateGreaterCloseDate {
            get {
                return ResourceManager.GetString("StartDateGreaterCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already voted for this election.
        /// </summary>
        public static string VoteAlreadyDone {
            get {
                return ResourceManager.GetString("VoteAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Completed.
        /// </summary>
        public static string VoteComplete {
            get {
                return ResourceManager.GetString("VoteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Error.
        /// </summary>
        public static string VoteError {
            get {
                return ResourceManager.GetString("VoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,the time allowed to vote for this election has been expired.
        /// </summary>
        public static string VoteExpired {
            get {
                return ResourceManager.GetString("VoteExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vote is not exists.
        /// </summary>
        public static string VoteNotExist {
            get {
                return ResourceManager.GetString("VoteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank your for your time ,your vote is saved successfully.
        /// </summary>
        public static string VoteSucessMessage {
            get {
                return ResourceManager.GetString("VoteSucessMessage", resourceCulture);
            }
        }
    }
}
