//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Areas.PRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataPhotograph
    {
        public System.Guid PhotoGUID { get; set; }
        public System.Guid IndividualGUID { get; set; }
        public bool PhotoActive { get; set; }
        public short PhotoTypeCode { get; set; }
        public Nullable<System.DateTime> PhotoDateStart { get; set; }
        public Nullable<System.DateTime> PhotoDateEnd { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoComments { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserIDUpdate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string SiteIDCreate { get; set; }
        public string SiteIDUpdate { get; set; }
        public string SiteIDOwner { get; set; }
        public System.DateTime OwnerDate { get; set; }
        public string SiteIDReplicate { get; set; }
    
        public virtual dataIndividual dataIndividual { get; set; }
    }
}
