//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Areas.PRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataIndividualV4
    {
        public string SiteIDOwner { get; set; }
        public System.Guid IndividualGUID { get; set; }
        public string ProcessingGroupNumber { get; set; }
        public string IndividualID { get; set; }
        public string GivenName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string MiddleName { get; set; }
        public string FamilyName { get; set; }
        public string SecondFamilyName { get; set; }
        public string VerbalName { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> CaseCreatedOn { get; set; }
        public Nullable<int> ProcessingGroupSize { get; set; }
        public Nullable<int> TotalSize { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string BirthCountryCode { get; set; }
        public string BirthCityTownVillage { get; set; }
        public string OriginCountryCode { get; set; }
        public string SexCode { get; set; }
        public Nullable<short> IndividualAge { get; set; }
        public string NationalityCode { get; set; }
        public string Relationship { get; set; }
        public string ProcessStatusCode { get; set; }
        public string Current_process_StatusCode { get; set; }
        public Nullable<System.DateTime> Current_process_StatusDate { get; set; }
        public string RefugeeStatusCode { get; set; }
        public Nullable<System.DateTime> RefugeeStatusDate { get; set; }
        public string RefStatCategoryCode { get; set; }
        public string LegalBasis { get; set; }
        public string IndividualAgeCohortCode { get; set; }
        public string MarriageStatusCode { get; set; }
        public string ReligionCode { get; set; }
        public string Religion { get; set; }
        public string EthnicityCode { get; set; }
        public string Ethnicity { get; set; }
        public string OccupationCode { get; set; }
        public string Occupation { get; set; }
        public string EducationLevelCode { get; set; }
        public Nullable<bool> HasSPNeed { get; set; }
        public string ConcatenatedName { get; set; }
        public Nullable<int> IndividualIDLegacy { get; set; }
        public string ProcessingGroupLegacyID { get; set; }
        public string IndComments { get; set; }
        public string CaseComments { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ProcessStatusReasonCode { get; set; }
        public Nullable<int> AddressType { get; set; }
        public Nullable<int> AddressCountry { get; set; }
        public string LocationLevel1ID { get; set; }
        public string LocationLevel2ID { get; set; }
        public string LocationLevel3ID { get; set; }
        public string LocationLevel4ID { get; set; }
        public string CoO_L1 { get; set; }
        public string CoO_L2 { get; set; }
        public string CoO_L3 { get; set; }
        public string CoO_L4 { get; set; }
        public string CoO_L6 { get; set; }
        public string CoOPhone { get; set; }
        public string CoA_AddressType { get; set; }
        public string CoA_AddressCountry { get; set; }
        public string COA_L1 { get; set; }
        public string COA_L2 { get; set; }
        public string COA_L3 { get; set; }
        public string COA_L4 { get; set; }
        public string CoA_LocationLevelCodeSoftField1 { get; set; }
        public string CoA_LocationLevelCodeSoftField2 { get; set; }
        public string CoA_Phone { get; set; }
        public string CoA { get; set; }
        public Nullable<int> NRefStatCategory { get; set; }
        public Nullable<int> NRefStatus { get; set; }
        public Nullable<System.DateTime> ProcessStatusChanged { get; set; }
        public Nullable<int> ProcessStatusChangeReason { get; set; }
        public string CommonlyUsedName { get; set; }
        public Nullable<int> ConcatenatedAlias { get; set; }
        public string RSDStatusCode { get; set; }
        public string ResettlementStatusCode { get; set; }
        public string RelationshipText { get; set; }
        public string BiometricId { get; set; }
        public Nullable<System.Guid> BusinessUnitGUID { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> ProcessingGroupGUID { get; set; }
        public string CoAEntryPoint { get; set; }
        public Nullable<System.Guid> V3GUID { get; set; }
        public Nullable<System.Guid> V4GUID { get; set; }
        public string changeReason { get; set; }
    }
}
