//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Areas.PRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataProcessGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataProcessGroup()
        {
            this.dataIndividualProcessGroup = new HashSet<dataIndividualProcessGroup>();
        }
    
        public System.Guid ProcessingGroupGUID { get; set; }
        public short ProcessingGroupTypeCode { get; set; }
        public string ProcessingGroupNumber { get; set; }
        public string ProcessingGroupLegacyID { get; set; }
        public string ProcessingGroupGovtNumber { get; set; }
        public string ProcessingGroupFormNumber { get; set; }
        public string CurrentRationCardNumber { get; set; }
        public Nullable<bool> ProcessingGroupActive { get; set; }
        public Nullable<System.DateTime> ProcessingGroupDeactiveDate { get; set; }
        public short ProcessingGroupSize { get; set; }
        public Nullable<short> DeclaredSize { get; set; }
        public short TotalGroupSize { get; set; }
        public Nullable<System.Guid> OriginalProcessingGroupGUID { get; set; }
        public string ResponsibleUserID { get; set; }
        public Nullable<short> CaseTypeCode { get; set; }
        public System.DateTime ProcessingGroupRegistrationDate { get; set; }
        public string CaseSource { get; set; }
        public string ProcessingGroupStatusCode { get; set; }
        public System.DateTime ProcessGroupStatusDate { get; set; }
        public Nullable<System.Guid> Level1RegistrationGUID { get; set; }
        public string ProcessingGroupComments { get; set; }
        public string PhyFile { get; set; }
        public string LastEventID { get; set; }
        public Nullable<System.DateTime> LastEventEffectiveDate { get; set; }
        public string WillingToReturnCode { get; set; }
        public string WillingToReturnConditions { get; set; }
        public string PGCompositionCode { get; set; }
        public string BiometricReferenceID { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserIDUpdate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string SiteIDCreate { get; set; }
        public string SiteIDUpdate { get; set; }
        public string SiteIDOwner { get; set; }
        public System.DateTime OwnerDate { get; set; }
        public string SiteIDReplicate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataIndividualProcessGroup> dataIndividualProcessGroup { get; set; }
    }
}
