//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsPortal.Areas.PRG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AppsPortal.Areas.PRG.Models;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PRGEntities : DbContext
    {
        public PRGEntities()
            : base(ConnectionString.Connect("ProGres"))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dataIndividual> dataIndividual { get; set; }
        public virtual DbSet<dataIndividualProcessGroup> dataIndividualProcessGroup { get; set; }
        public virtual DbSet<dataPhotograph> dataPhotograph { get; set; }
        public virtual DbSet<dataProcessGroup> dataProcessGroup { get; set; }
        public virtual DbSet<codeProcessStatus> codeProcessStatus { get; set; }
        public virtual DbSet<dataDocument> dataDocument { get; set; }
        public virtual DbSet<codeDocumentTypeText> codeDocumentTypeText { get; set; }
        public virtual DbSet<codeProcessStatusText> codeProcessStatusText { get; set; }
        public virtual DbSet<configSecurityUser> configSecurityUser { get; set; }
        public virtual DbSet<dataIndividualV4> dataIndividualV4 { get; set; }
        public virtual DbSet<dataProcessGroupV4> dataProcessGroupV4 { get; set; }
    
        public virtual int rspUpdateDocument(string hH, string uS, string lT, string nD, string dT)
        {
            var hHParameter = hH != null ?
                new ObjectParameter("HH", hH) :
                new ObjectParameter("HH", typeof(string));
    
            var uSParameter = uS != null ?
                new ObjectParameter("US", uS) :
                new ObjectParameter("US", typeof(string));
    
            var lTParameter = lT != null ?
                new ObjectParameter("LT", lT) :
                new ObjectParameter("LT", typeof(string));
    
            var nDParameter = nD != null ?
                new ObjectParameter("ND", nD) :
                new ObjectParameter("ND", typeof(string));
    
            var dTParameter = dT != null ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rspUpdateDocument", hHParameter, uSParameter, lTParameter, nDParameter, dTParameter);
        }
    }
}
