
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMD_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class v_dataPartnerMonitoringDatabase2022DataTable
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "EDMXID", ResourceType = typeof(resxDbFields))]
    	public int EDMXID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "PartnerMonitoringDBGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid PartnerMonitoringDBGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "DateOfReport", ResourceType = typeof(resxDbFields))]
    	public System.DateTime DateOfReport{ get; set; }
    	
        [Display(Name = "GovernorateGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> GovernorateGUID{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Governorate", ResourceType = typeof(resxDbFields))]
    	public string Governorate{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "admin1Name_en", ResourceType = typeof(resxDbFields))]
    	public string admin1Name_en{ get; set; }
    	
        [StringLength(300, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "District", ResourceType = typeof(resxDbFields))]
    	public string District{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "admin2Name_en", ResourceType = typeof(resxDbFields))]
    	public string admin2Name_en{ get; set; }
    	
        [StringLength(300, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "SubDistrict", ResourceType = typeof(resxDbFields))]
    	public string SubDistrict{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "admin3Name_en", ResourceType = typeof(resxDbFields))]
    	public string admin3Name_en{ get; set; }
    	
        [StringLength(300, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CommunityName", ResourceType = typeof(resxDbFields))]
    	public string CommunityName{ get; set; }
    	
        [StringLength(200, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "admin4Name_en", ResourceType = typeof(resxDbFields))]
    	public string admin4Name_en{ get; set; }
    	
        [StringLength(300, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Neighborhood", ResourceType = typeof(resxDbFields))]
    	public string Neighborhood{ get; set; }
    	
        [StringLength(300, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Location", ResourceType = typeof(resxDbFields))]
    	public string Location{ get; set; }
    	
        [Display(Name = "Longitude", ResourceType = typeof(resxDbFields))]
    	public Nullable<double> Longitude{ get; set; }
    	
        [Display(Name = "Latitude", ResourceType = typeof(resxDbFields))]
    	public Nullable<double> Latitude{ get; set; }
    	
        [Display(Name = "PMDCommunityCenterGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> PMDCommunityCenterGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "OutcomeGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid OutcomeGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(500, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "OutcomeDescription", ResourceType = typeof(resxDbFields))]
    	public string OutcomeDescription{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "OutputGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid OutputGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(500, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "OutputDescription", ResourceType = typeof(resxDbFields))]
    	public string OutputDescription{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IndicatorGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid IndicatorGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(500, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IndicatorDescription", ResourceType = typeof(resxDbFields))]
    	public string IndicatorDescription{ get; set; }
    	
        [Display(Name = "MeasurementTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> MeasurementTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IsDirectActivity", ResourceType = typeof(resxDbFields))]
    	public bool IsDirectActivity{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ImplementingPartnerGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid ImplementingPartnerGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(256, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "PartnerDescription", ResourceType = typeof(resxDbFields))]
    	public string PartnerDescription{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(101, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CreatedByName", ResourceType = typeof(resxDbFields))]
    	public string CreatedByName{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CreatedBy", ResourceType = typeof(resxDbFields))]
    	public System.Guid CreatedBy{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "CreatedOn", ResourceType = typeof(resxDbFields))]
    	public System.DateTime CreatedOn{ get; set; }
    	
        [Display(Name = "UpdatedBy", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> UpdatedBy{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "UpdatedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> UpdatedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "UpdatedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalUpdatedOn { get { return new Portal().LocalTime(this.UpdatedOn); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(20, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VerificationStatusText", ResourceType = typeof(resxDbFields))]
    	public string VerificationStatusText{ get; set; }
    	
        [Display(Name = "IsVerifiedByFieldTech", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> IsVerifiedByFieldTech{ get; set; }
    	
        [Display(Name = "VerifiedByFieldTechGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> VerifiedByFieldTechGUID{ get; set; }
    	
        [StringLength(101, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "VerifiedByFullName", ResourceType = typeof(resxDbFields))]
    	public string VerifiedByFullName{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "VerifiedByFieldTechOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> VerifiedByFieldTechOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "VerifiedByFieldTechOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalVerifiedByFieldTechOn { get { return new Portal().LocalTime(this.VerifiedByFieldTechOn); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(16, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ApprovalStatusText", ResourceType = typeof(resxDbFields))]
    	public string ApprovalStatusText{ get; set; }
    	
        [Display(Name = "IsApprovedByCountryTech", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> IsApprovedByCountryTech{ get; set; }
    	
        [Display(Name = "ApprovedByCountryTechGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> ApprovedByCountryTechGUID{ get; set; }
    	
        [StringLength(101, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ApprovedByFullName", ResourceType = typeof(resxDbFields))]
    	public string ApprovedByFullName{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ApprovedByCountryTechOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ApprovedByCountryTechOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ApprovedByCountryTechOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalApprovedByCountryTechOn { get { return new Portal().LocalTime(this.ApprovedByCountryTechOn); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IsVerified", ResourceType = typeof(resxDbFields))]
    	public bool IsVerified{ get; set; }
    	
        [Display(Name = "VerifiedBy", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> VerifiedBy{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "VerifiedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> VerifiedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "VerifiedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalVerifiedOn { get { return new Portal().LocalTime(this.VerifiedOn); } }
    	
        [Display(Name = "RefTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> RefTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasRefTotal", ResourceType = typeof(resxDbFields))]
    	public string HasRefTotal{ get; set; }
    	
        [Display(Name = "IdpTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> IdpTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasIdpTotal", ResourceType = typeof(resxDbFields))]
    	public string HasIdpTotal{ get; set; }
    	
        [Display(Name = "IdpRetTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> IdpRetTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasIdpRetTotal", ResourceType = typeof(resxDbFields))]
    	public string HasIdpRetTotal{ get; set; }
    	
        [Display(Name = "RefRetTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> RefRetTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasRefRetTotal", ResourceType = typeof(resxDbFields))]
    	public string HasRefRetTotal{ get; set; }
    	
        [Display(Name = "AsrTotal", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> AsrTotal{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasAsrTotal", ResourceType = typeof(resxDbFields))]
    	public string HasAsrTotal{ get; set; }
    	
        [Display(Name = "HostCommunity", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> HostCommunity{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasHostCommunity", ResourceType = typeof(resxDbFields))]
    	public string HasHostCommunity{ get; set; }
    	
        [Display(Name = "OtherTotalNes", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> OtherTotalNes{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasOtherTotalNes", ResourceType = typeof(resxDbFields))]
    	public string HasOtherTotalNes{ get; set; }
    	
        [Display(Name = "Boys", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> Boys{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasBoys", ResourceType = typeof(resxDbFields))]
    	public string HasBoys{ get; set; }
    	
        [Display(Name = "Girls", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> Girls{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasGirls", ResourceType = typeof(resxDbFields))]
    	public string HasGirls{ get; set; }
    	
        [Display(Name = "Men", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> Men{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasMen", ResourceType = typeof(resxDbFields))]
    	public string HasMen{ get; set; }
    	
        [Display(Name = "Women", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> Women{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasWomen", ResourceType = typeof(resxDbFields))]
    	public string HasWomen{ get; set; }
    	
        [Display(Name = "ElderlyWomen", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ElderlyWomen{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasElderlyWomen", ResourceType = typeof(resxDbFields))]
    	public string HasElderlyWomen{ get; set; }
    	
        [Display(Name = "ElderlyMen", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ElderlyMen{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(5, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "HasElderlyMen", ResourceType = typeof(resxDbFields))]
    	public string HasElderlyMen{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(8, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "dataPartnerMonitoring2022DBRowVersion", ResourceType = typeof(resxDbFields))]
    	public byte[] dataPartnerMonitoring2022DBRowVersion{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "LanguageID", ResourceType = typeof(resxDbFields))]
    	public string LanguageID{ get; set; }
    	
    }
}
