
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTP_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataPersonalHistoryLanguage
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "GTPPHLanguageGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid GTPPHLanguageGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "GTPApplicationGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid GTPApplicationGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "MotherTongueLanguageGUID", ResourceType = typeof(resxDbFields))]
    	public string MotherTongueLanguageGUID{ get; set; }
    	
        [Display(Name = "MotherTongueLanguageReadingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> MotherTongueLanguageReadingGUID{ get; set; }
    	
        [Display(Name = "MotherTongueLanguageSpeakingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> MotherTongueLanguageSpeakingGUID{ get; set; }
    	
        [Display(Name = "MotherTongueLanguageWritingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> MotherTongueLanguageWritingGUID{ get; set; }
    	
        [Display(Name = "MotherTongueLanguageListeningGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> MotherTongueLanguageListeningGUID{ get; set; }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "SecondLanguageGUID", ResourceType = typeof(resxDbFields))]
    	public string SecondLanguageGUID{ get; set; }
    	
        [Display(Name = "SecondLanguageReadingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> SecondLanguageReadingGUID{ get; set; }
    	
        [Display(Name = "SecondLanguageSpeakingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> SecondLanguageSpeakingGUID{ get; set; }
    	
        [Display(Name = "SecondLanguageWritingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> SecondLanguageWritingGUID{ get; set; }
    	
        [Display(Name = "SecondLanguageListeningGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> SecondLanguageListeningGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "SecondLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> SecondLanguageEvaluationDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "SecondLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalSecondLanguageEvaluationDate { get { return new Portal().LocalTime(this.SecondLanguageEvaluationDate); } }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ThirdLanguageGUID", ResourceType = typeof(resxDbFields))]
    	public string ThirdLanguageGUID{ get; set; }
    	
        [Display(Name = "ThirdLanguageReadingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> ThirdLanguageReadingGUID{ get; set; }
    	
        [Display(Name = "ThirdLanguageSpeakingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> ThirdLanguageSpeakingGUID{ get; set; }
    	
        [Display(Name = "ThirdLanguageWritingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> ThirdLanguageWritingGUID{ get; set; }
    	
        [Display(Name = "ThirdLanguageListeningGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> ThirdLanguageListeningGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ThirdLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ThirdLanguageEvaluationDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ThirdLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalThirdLanguageEvaluationDate { get { return new Portal().LocalTime(this.ThirdLanguageEvaluationDate); } }
    	
        [StringLength(100, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "FourthLanguageGUID", ResourceType = typeof(resxDbFields))]
    	public string FourthLanguageGUID{ get; set; }
    	
        [Display(Name = "FourthLanguageReadingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> FourthLanguageReadingGUID{ get; set; }
    	
        [Display(Name = "FourthLanguageSpeakingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> FourthLanguageSpeakingGUID{ get; set; }
    	
        [Display(Name = "FourthLanguageWritingGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> FourthLanguageWritingGUID{ get; set; }
    	
        [Display(Name = "FourthLanguageListeningGUID", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.Guid> FourthLanguageListeningGUID{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "FourthLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> FourthLanguageEvaluationDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "FourthLanguageEvaluationDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalFourthLanguageEvaluationDate { get { return new Portal().LocalTime(this.FourthLanguageEvaluationDate); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataPersonalHistoryLanguageRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
    
        public virtual dataGTPApplication dataGTPApplication { get; set; }
    }
}
