//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userPersonalDetailsLanguage> userPersonalDetailsLanguage { get; set; }
        public virtual DbSet<codeJobTitles> codeJobTitles { get; set; }
        public virtual DbSet<codeJobTitlesLanguages> codeJobTitlesLanguages { get; set; }
        public virtual DbSet<StaffCoreData> StaffCoreData { get; set; }
        public virtual DbSet<codeOfficeFloor> codeOfficeFloor { get; set; }
        public virtual DbSet<codeOfficeFloorRoom> codeOfficeFloorRoom { get; set; }
        public virtual DbSet<codeOffices> codeOffices { get; set; }
        public virtual DbSet<dataOfficeStaffAttendance> dataOfficeStaffAttendance { get; set; }
        public virtual DbSet<dataOfficeStaffAttendanceConfirmation> dataOfficeStaffAttendanceConfirmation { get; set; }
    }
}
