
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataElectionStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataElectionStaff()
        {
            this.dataElectionCorrespondenceStaff = new HashSet<dataElectionCorrespondenceStaff>();
            this.dataStaffVote = new HashSet<dataStaffVote>();
        }
    
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ElectionStaffGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid ElectionStaffGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ElectionGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid ElectionGUID{ get; set; }
    	
        [StringLength(40, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "AccessKey", ResourceType = typeof(resxDbFields))]
    	public string AccessKey{ get; set; }
    	
        [StringLength(50, ErrorMessageResourceName = "StringLengthMax", ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "IPAddress", ResourceType = typeof(resxDbFields))]
    	public string IPAddress{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "VoteDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> VoteDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "VoteDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalVoteDate { get { return new Portal().LocalTime(this.VoteDate); } }
    	
        [Display(Name = "IsViewed", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> IsViewed{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "ViewedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> ViewedDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "ViewedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalViewedDate { get { return new Portal().LocalTime(this.ViewedDate); } }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "StaffGUID", ResourceType = typeof(resxDbFields))]
    	public System.Guid StaffGUID{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataElectionStaffRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
    
        public virtual dataElection dataElection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataElectionCorrespondenceStaff> dataElectionCorrespondenceStaff { get; set; }
        public virtual dataStaff dataStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataStaffVote> dataStaffVote { get; set; }
    }
}
