//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DASEntities : DbContext
    {
        public DASEntities()
            : base("name=DASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<userAccounts> userAccounts { get; set; }
        public DbSet<userPersonalDetails> userPersonalDetails { get; set; }
        public DbSet<userPersonalDetailsLanguage> userPersonalDetailsLanguage { get; set; }
        public DbSet<codeDASDestinationUnit> codeDASDestinationUnit { get; set; }
        public DbSet<codeDASDestinationUnitFocalPoint> codeDASDestinationUnitFocalPoint { get; set; }
        public DbSet<codeDASDocumentCabinetShelf> codeDASDocumentCabinetShelf { get; set; }
        public DbSet<codeDASDocumentMetaData> codeDASDocumentMetaData { get; set; }
        public DbSet<codeDASDocumentSourceType> codeDASDocumentSourceType { get; set; }
        public DbSet<codeDASTransferLocation> codeDASTransferLocation { get; set; }
        public DbSet<codeDutyStations> codeDutyStations { get; set; }
        public DbSet<codeDutyStationsConfigurations> codeDutyStationsConfigurations { get; set; }
        public DbSet<codeDutyStationsLanguages> codeDutyStationsLanguages { get; set; }
        public DbSet<dataDefaultScannerSetting> dataDefaultScannerSetting { get; set; }
        public DbSet<dataFile> dataFile { get; set; }
        public DbSet<dataFileLocationMovement> dataFileLocationMovement { get; set; }
        public DbSet<dataFileRequest> dataFileRequest { get; set; }
        public DbSet<dataReportTemplateConfiguration> dataReportTemplateConfiguration { get; set; }
        public DbSet<dataScannDocument> dataScannDocument { get; set; }
        public DbSet<dataScannDocumentImage> dataScannDocumentImage { get; set; }
        public DbSet<dataScannDocumentImageMetaData> dataScannDocumentImageMetaData { get; set; }
        public DbSet<dataScannDocumentImageVersionHistory> dataScannDocumentImageVersionHistory { get; set; }
        public DbSet<dataScannDocumentMetaData> dataScannDocumentMetaData { get; set; }
        public DbSet<dataScannDocumentStatusFlow> dataScannDocumentStatusFlow { get; set; }
        public DbSet<dataScannDocumentTransfer> dataScannDocumentTransfer { get; set; }
        public DbSet<dataScannDocumentTransferFlow> dataScannDocumentTransferFlow { get; set; }
        public DbSet<dataScannDocumentVersionHistory> dataScannDocumentVersionHistory { get; set; }
        public DbSet<dataSchedulerCasesHaveAppointment> dataSchedulerCasesHaveAppointment { get; set; }
        public DbSet<dataTempScannDocumentImage> dataTempScannDocumentImage { get; set; }
        public DbSet<dataUploadUserFile> dataUploadUserFile { get; set; }
        public DbSet<dataOldFTSFileMovement> dataOldFTSFileMovement { get; set; }
        public DbSet<dataReportTemplate> dataReportTemplate { get; set; }
        public DbSet<codeTables> codeTables { get; set; }
        public DbSet<codeTablesValues> codeTablesValues { get; set; }
        public DbSet<codeTablesValuesLanguages> codeTablesValuesLanguages { get; set; }
        public DbSet<userServiceHistory> userServiceHistory { get; set; }
        public DbSet<codeDASTemplateType> codeDASTemplateType { get; set; }
        public DbSet<codeDASTemplateTypeDocument> codeDASTemplateTypeDocument { get; set; }
        public DbSet<codeDASTemplateTypeDocumentSoftField> codeDASTemplateTypeDocumentSoftField { get; set; }
        public DbSet<codeDASTemplateTypeDocumentTag> codeDASTemplateTypeDocumentTag { get; set; }
        public DbSet<dataArchiveTemplate> dataArchiveTemplate { get; set; }
        public DbSet<dataArchiveTemplateDocumentImageVersionHistory> dataArchiveTemplateDocumentImageVersionHistory { get; set; }
        public DbSet<dataArchiveTemplateDocumentSoftField> dataArchiveTemplateDocumentSoftField { get; set; }
        public DbSet<dataArchiveTemplateDocumentTag> dataArchiveTemplateDocumentTag { get; set; }
        public DbSet<dataArchiveTemplateDocumentVersionHistory> dataArchiveTemplateDocumentVersionHistory { get; set; }
        public DbSet<dataArchiveTemplateFlowVerification> dataArchiveTemplateFlowVerification { get; set; }
        public DbSet<v_TrackTransferFilesMovement> v_TrackTransferFilesMovement { get; set; }
        public DbSet<dataArchiveTemplateDocumentImage> dataArchiveTemplateDocumentImage { get; set; }
        public DbSet<dataAuditActions> dataAuditActions { get; set; }
        public DbSet<userProfiles> userProfiles { get; set; }
        public DbSet<codeActions> codeActions { get; set; }
        public DbSet<codeActionsVerbsLanguages> codeActionsVerbsLanguages { get; set; }
        public DbSet<StaffCoreData> StaffCoreData { get; set; }
        public DbSet<dataArchiveTemplateDocumentLink> dataArchiveTemplateDocumentLink { get; set; }
        public DbSet<dataArchiveTemplateDocument> dataArchiveTemplateDocument { get; set; }
        public DbSet<codeDASDocumentCabinet> codeDASDocumentCabinet { get; set; }
    }
}
