
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS_DAL.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RES_Repo.Globalization;
    using System.ComponentModel.DataAnnotations.Schema;
    using Portal_BL.Library;
    
    public partial class dataReportTemplate
    {
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ReportTemplateId", ResourceType = typeof(resxDbFields))]
    	public int ReportTemplateId{ get; set; }
    	
        [Display(Name = "Name", ResourceType = typeof(resxDbFields))]
    	public string Name{ get; set; }
    	
        [Display(Name = "Description", ResourceType = typeof(resxDbFields))]
    	public string Description{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "GeneratedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> GeneratedDate{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "GeneratedDate", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalGeneratedDate { get { return new Portal().LocalTime(this.GeneratedDate); } }
    	
        [Display(Name = "ReportCategoryId", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ReportCategoryId{ get; set; }
    	
        [Display(Name = "ReviewsCount", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ReviewsCount{ get; set; }
    	
        [Display(Name = "ReportTypeId", ResourceType = typeof(resxDbFields))]
    	public Nullable<int> ReportTypeId{ get; set; }
    	
        [Display(Name = "ReportQuery", ResourceType = typeof(resxDbFields))]
    	public string ReportQuery{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "ReportId", ResourceType = typeof(resxDbFields))]
    	public int ReportId{ get; set; }
    	
        [Required(ErrorMessageResourceName = "RequiredField" , ErrorMessageResourceType = typeof(resxHttpErrors))]
    	[Display(Name = "Active", ResourceType = typeof(resxDbFields))]
    	public bool Active{ get; set; }
    	
        public byte[] dataReportTemplateRowVersion{ get; set; }
    	
        [DataType(DataType.DateTime)]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> DeletedOn{ get; set; }
    	
    	[NotMapped]
    	[Display(Name = "DeletedOn", ResourceType = typeof(resxDbFields))]
    	public Nullable<System.DateTime> LocalDeletedOn { get { return new Portal().LocalTime(this.DeletedOn); } }
    	
        [Display(Name = "Archived", ResourceType = typeof(resxDbFields))]
    	public Nullable<bool> Archived{ get; set; }
    	
    }
}
