//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeWarehouseItemModelFeature
    {
        public System.Guid WarehouseItemModelFeatureGUID { get; set; }
        public Nullable<System.Guid> WarehouseItemModelGUID { get; set; }
        public Nullable<System.Guid> WarehouseGeneralFeatureGUID { get; set; }
        public string FeatureValue { get; set; }
        public bool Active { get; set; }
        public byte[] codeWarehouseItemModelFeatureRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual codeWarehouseGeneralFeature codeWarehouseGeneralFeature { get; set; }
        public virtual codeWarehouseItemModel codeWarehouseItemModel { get; set; }
    }
}
