//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeLocationsLanguages
    {
        public System.Guid LocationLanguageGUID { get; set; }
        public System.Guid LocationGUID { get; set; }
        public string LanguageID { get; set; }
        public string LocationDescription { get; set; }
        public bool Active { get; set; }
        public byte[] codeLocationsLanguagesRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual codeLocations codeLocations { get; set; }
    }
}
