//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeWarehouseItemModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeWarehouseItemModel()
        {
            this.codeItemModelWarehouse = new HashSet<codeItemModelWarehouse>();
            this.codeWarehouseItemModelLanguage = new HashSet<codeWarehouseItemModelLanguage>();
            this.codeWarehouseItemModel1 = new HashSet<codeWarehouseItemModel>();
            this.codeWarehouseItemModelDeterminant = new HashSet<codeWarehouseItemModelDeterminant>();
            this.codeWarehouseItemModelFeature = new HashSet<codeWarehouseItemModelFeature>();
        }
    
        public System.Guid WarehouseItemModelGUID { get; set; }
        public System.Guid WarehouseItemGUID { get; set; }
        public Nullable<System.Guid> BrandGUID { get; set; }
        public bool Active { get; set; }
        public byte[] codeWarehouseItemModelRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.Guid> ItemModelRelationTypeGUID { get; set; }
        public Nullable<System.Guid> ParentWarehouseItemModelGUID { get; set; }
    
        public virtual codeBrand codeBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeItemModelWarehouse> codeItemModelWarehouse { get; set; }
        public virtual codeWarehouseItem codeWarehouseItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouseItemModelLanguage> codeWarehouseItemModelLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouseItemModel> codeWarehouseItemModel1 { get; set; }
        public virtual codeWarehouseItemModel codeWarehouseItemModel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouseItemModelDeterminant> codeWarehouseItemModelDeterminant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouseItemModelFeature> codeWarehouseItemModelFeature { get; set; }
    }
}
