//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class codeWMSFeatureTypeValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codeWMSFeatureTypeValue()
        {
            this.dataItemInputDetailFeature = new HashSet<dataItemInputDetailFeature>();
        }
    
        public System.Guid FeatureTypeValueGUID { get; set; }
        public Nullable<System.Guid> FeatureTypeGUID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> HasValue { get; set; }
        public bool Active { get; set; }
        public byte[] codeWMSFeatureTypeValueRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual codeWMSFeatureType codeWMSFeatureType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInputDetailFeature> dataItemInputDetailFeature { get; set; }
    }
}
