//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataItemOutputDetailFlow
    {
        public System.Guid ItemOutputDetailFlowGUID { get; set; }
        public Nullable<System.Guid> ItemOutputDetailGUID { get; set; }
        public Nullable<System.Guid> ItemStatuGUID { get; set; }
        public Nullable<System.Guid> FlowTypeGUID { get; set; }
        public Nullable<bool> IsLastAction { get; set; }
        public Nullable<bool> IsLastMove { get; set; }
        public Nullable<System.Guid> CreatedByGUID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
        public byte[] dataItemOutputDetailFlowRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
        public string Comments { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual userAccounts userAccounts { get; set; }
        public virtual dataItemOutputDetail dataItemOutputDetail { get; set; }
    }
}
