//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataLicenseSubscriptionContractPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataLicenseSubscriptionContractPO()
        {
            this.dataLicenseSubscriptionContractPOFile = new HashSet<dataLicenseSubscriptionContractPOFile>();
        }
    
        public System.Guid LicenseSubscriptionContractPOGUID { get; set; }
        public Nullable<System.Guid> LicenseSubscriptionContractGUID { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string PODescription { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateByGUID { get; set; }
        public Nullable<System.Guid> UpdateByGUID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public byte[] dataLicenseSubscriptionContractPORowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> Archived { get; set; }
    
        public virtual dataLicenseSubscriptionContract dataLicenseSubscriptionContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataLicenseSubscriptionContractPOFile> dataLicenseSubscriptionContractPOFile { get; set; }
    }
}
