//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userAccounts()
        {
            this.codeWarehouseFocalPoint = new HashSet<codeWarehouseFocalPoint>();
            this.dataWarehouseFocalPoint = new HashSet<dataWarehouseFocalPoint>();
            this.dataItemInput = new HashSet<dataItemInput>();
            this.dataItemInputDetail = new HashSet<dataItemInputDetail>();
            this.dataItemInputDetail1 = new HashSet<dataItemInputDetail>();
            this.dataItemInputDeterminant = new HashSet<dataItemInputDeterminant>();
            this.dataItemInputFlow = new HashSet<dataItemInputFlow>();
            this.dataItemIntpuDetailUploadedDocument = new HashSet<dataItemIntpuDetailUploadedDocument>();
            this.dataItemOutput = new HashSet<dataItemOutput>();
            this.dataItemOutputDetail = new HashSet<dataItemOutputDetail>();
            this.dataItemOutputDetailFlow = new HashSet<dataItemOutputDetailFlow>();
            this.dataItemOutputFlow = new HashSet<dataItemOutputFlow>();
            this.dataItemOutputFlow1 = new HashSet<dataItemOutputFlow>();
            this.dataItemRequestFlow = new HashSet<dataItemRequestFlow>();
            this.dataItemOutputNotification = new HashSet<dataItemOutputNotification>();
            this.dataItemRequest = new HashSet<dataItemRequest>();
            this.dataItemRequestFlow1 = new HashSet<dataItemRequestFlow>();
            this.dataItemReservation = new HashSet<dataItemReservation>();
            this.dataItemTransfer = new HashSet<dataItemTransfer>();
            this.dataItemTransfer1 = new HashSet<dataItemTransfer>();
            this.dataItemVerificationPeriodDetail = new HashSet<dataItemVerificationPeriodDetail>();
            this.dataItemOutputDetailDamagedTrack = new HashSet<dataItemOutputDetailDamagedTrack>();
            this.dataItemOutputDetailDamagedTrack1 = new HashSet<dataItemOutputDetailDamagedTrack>();
        }
    
        public System.Guid UserGUID { get; set; }
        public string TimeZone { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public System.Guid SecurityQuestionGUID { get; set; }
        public string SecurityAnswer { get; set; }
        public int AccountStatusID { get; set; }
        public bool IsFirstLogin { get; set; }
        public Nullable<bool> HasPhoto { get; set; }
        public bool Active { get; set; }
        public byte[] userAccountsRowVersion { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codeWarehouseFocalPoint> codeWarehouseFocalPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataWarehouseFocalPoint> dataWarehouseFocalPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInput> dataItemInput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInputDetail> dataItemInputDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInputDetail> dataItemInputDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInputDeterminant> dataItemInputDeterminant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemInputFlow> dataItemInputFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemIntpuDetailUploadedDocument> dataItemIntpuDetailUploadedDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutput> dataItemOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputDetail> dataItemOutputDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputDetailFlow> dataItemOutputDetailFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputFlow> dataItemOutputFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputFlow> dataItemOutputFlow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemRequestFlow> dataItemRequestFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputNotification> dataItemOutputNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemRequest> dataItemRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemRequestFlow> dataItemRequestFlow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemReservation> dataItemReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemTransfer> dataItemTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemTransfer> dataItemTransfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemVerificationPeriodDetail> dataItemVerificationPeriodDetail { get; set; }
        public virtual userPersonalDetails userPersonalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputDetailDamagedTrack> dataItemOutputDetailDamagedTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataItemOutputDetailDamagedTrack> dataItemOutputDetailDamagedTrack1 { get; set; }
    }
}
