//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TrackSIMCardRoamingDetail
    {
        public Nullable<long> RowId { get; set; }
        public System.Guid ItemOutputDetailFlowGUID { get; set; }
        public string ItemGroup { get; set; }
        public string ModelName { get; set; }
        public string CurrentCustodian { get; set; }
        public string GSM { get; set; }
        public string SerialNumber { get; set; }
        public string SIMPackageSize { get; set; }
        public Nullable<bool> HasRoaming { get; set; }
        public Nullable<bool> HasInternationalAccess { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public string DutyStation { get; set; }
        public Nullable<System.Guid> OrganizationInstanceGUID { get; set; }
        public string PackageSizeMain { get; set; }
    }
}
