//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_trackItemEntryMovementDataTable
    {
        public string WarehouseItemClassificationDescription { get; set; }
        public string WarehouseItemDescription { get; set; }
        public string ModelDescription { get; set; }
        public Nullable<System.Guid> ItemInputDetailGUID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> WarehouseItemClassificationGUID { get; set; }
        public Nullable<System.Guid> WarehouseItemGuid { get; set; }
        public Nullable<System.Guid> WarehouseItemModelGUID { get; set; }
        public Nullable<System.Guid> ItemModelWarehouseGUID { get; set; }
        public string BrandDescription { get; set; }
        public Nullable<System.Guid> BrandGUID { get; set; }
        public Nullable<System.Guid> WarehouseLocationGUID { get; set; }
        public Nullable<bool> IsAvaliable { get; set; }
        public Nullable<System.Guid> LastCustdianGUID { get; set; }
        public Nullable<System.Guid> LastFlowTypeGUID { get; set; }
        public string CreatedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> LastCustdianNameGUID { get; set; }
        public string LastCustodianName { get; set; }
        public Nullable<System.Guid> ItemStatusGUID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedByGUID { get; set; }
        public byte[] dataItemInputDetailRowVersion { get; set; }
        public Nullable<System.Guid> PurposeofuseGUID { get; set; }
        public string LastCustodian { get; set; }
        public string BarcodeNumber { get; set; }
        public string SerialNumber { get; set; }
        public string IMEI1 { get; set; }
        public string GSM { get; set; }
        public string MAC { get; set; }
        public string IMEI2 { get; set; }
        public string IMEI { get; set; }
        public string LastLocation { get; set; }
        public string LastFlow { get; set; }
        public string ItemStatus { get; set; }
        public string WarehosueOwnerName { get; set; }
        public Nullable<System.Guid> WarehouseOwnerGUID { get; set; }
        public string Purposeofuse { get; set; }
    }
}
